version: '2'
services:
  server:
    image: redash/redash:latest
    command: server
    network_mode: host
    container_name: redash-web
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://localhost:6379/0"
      REDASH_DATABASE_URL: "postgresql://user:password@localhost/redash"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 1
  worker:
    image: redash/redash:latest
    network_mode: host
    command: scheduler
    container_name: redash-worker
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://localhost:6379/0"
      REDASH_DATABASE_URL: "postgresql://user:password@localhost/redash"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 1
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
